# Generated by Django 5.2.12 on 2026-03-13 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_profile_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.FileField(blank=True, null=True, upload_to='profiles/avatars/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='banner',
            field=models.FileField(blank=True, null=True, upload_to='profiles/banners/'),
        ),
    ]
