# Generated by Django 5.2.6 on 2026-04-10 06:38

from django.db import migrations, models


def migrate_admin_role_to_manager(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    User.objects.filter(role="ADMIN").update(role="MANAGER")


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('MANAGER', 'Manager'), ('TEAM_LEAD', 'Team Lead'), ('EMPLOYEE', 'Employee')], default='EMPLOYEE', max_length=20),
        ),
        migrations.RunPython(migrate_admin_role_to_manager, migrations.RunPython.noop),
    ]
